import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import NeuralBackground from "@/components/NeuralBackground";
import Preloader from "@/components/Preloader";
import ClientOnly from "@/components/ClientOnly";
import Script from "next/script";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    template: "%s",
    default: "Ganin Vacheslav",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* Глобальный нейронный фон */}
        <ClientOnly>
          <NeuralBackground />
        </ClientOnly>
        
        {/* Прелоадер */}
        <ClientOnly>
          <Preloader />
        </ClientOnly>
        
        <Header />
        {children}
      </body>
    </html>
  );
}
